version: '3'

services:
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: 'nginx-mls'
        ports:
            - 8080:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
            - ./html:/www/static
        depends_on:
          - php
        networks:
            - internal

    php:
        image: php:fpm-alpine
        container_name: 'php-mls'
        volumes:
            - ./html:/www/static
        networks:
            - internal

networks:
    internal:
        driver: bridge
