version: "3"

services:
  nginx:
    image: alfg/nginx-rtmp:v1.6.0
    container_name: "nginx-mls"
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./html:/www/static
    depends_on:
      - php
    networks:
      - internal

  php:
    image: php:7.0-fpm-alpine
    container_name: "php-mls"
    volumes:
      - ./html:/www/static
    networks:
      - internal

networks:
  internal:
    driver: bridge
