import { Inter } from 'next/font/google';
import './globals.css';
import Head from 'next/head';
import Header from './header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Head>
                <title>My page title</title>
            </Head>
            <Header />
            <body className={inter.className + ' bg-base-100 text-base-content'}>{children}</body>
        </html>
    );
}
